version: "3.3"

services:
  app:
    build: .
    volumes:
      - "./nginx.conf:/app/nginx.conf"
      - "./supervisord.conf:/app/supervisord.conf"
      - "./uwsgi.ini:/app/uwsgi.ini"
    ports:
      - "8081:8080"