version: "3.3"

services:
  app:
    build: .
    volumes:
      - "./nginx.conf:/app/nginx.conf"
      - "./supervisord.conf:/app/supervisord.conf"
      - "./uwsgi.ini:/app/uwsgi.ini"
      - "./server.crt:/app/ssl/cert.pem:ro"
      - "./server.key:/app/ssl/cert.key:ro"